# Finding appropriate prior distributions based on Bobby's simulated annealing.

In our inference, we don't wish to only include likelihoods... we would also like to have more informed priors. Let's look at the data.

In [9]:
import sys, os
sys.path.append("..")
from utils import path as pth
from scipy.io import loadmat
import csv
import numpy as np
import pandas as pd

Two sets of parameters were found; one uses the same standard HCP connectome for all calculations, the other used individual patient connectomes for each parameter search.

In [2]:
HCP_params_path = '/Users/Megan/RajLab/BRAIN/SCFC-spectral-python/SCFC/data/SCFC_opparam_HCP.mat'
IndConn_params_path = '/Users/Megan/RajLab/BRAIN/SCFC-spectral-python/SCFC/data/SCFC_opparam_individual.mat'

In [3]:
HCPdata = loadmat(HCP_params_path)

In [4]:
HCPdata.keys()

dict_keys(['__header__', '__version__', '__globals__', 'output'])

In [7]:
HCPdata['output'].shape

(1, 39)

In [10]:
df = pd.DataFrame(HCPdata['output'][0])

In [13]:
df.head()

subjname                                              param  \
0  [8002.101]  [[0.012], [0.005], [0.5], [5.0], [4.0], [1.0],...   
1  [8008.101]  [[0.011934858833523522], [0.007416371455534797...   
2  [8012.101]  [[0.015953676157214023], [0.008954110012403716...   
3  [8027.101]  [[0.016012950820885972], [0.008461467268632639...   
4  [8028.101]  [[0.01565266891377659], [0.0061132652979348796...   

                     feval                                       simannealmsg  \
0  [[-0.8170847971245495]]  [[[[[3500]], [[3648]], ['Optimization terminat...   
1  [[-0.8481458299887372]]  [[[[[6706]], [[6973]], ['Optimization terminat...   
2  [[-0.8778002599935318]]  [[[[[4013]], [[4175]], ['Optimization terminat...   
3   [[-0.777688477204027]]  [[[[[7279]], [[7609]], ['Optimization terminat...   
4  [[-0.7898000029556442]]  [[[[[4912]], [[5123]], ['Optimization terminat...   

                                             cfevals  
0  [[-0.8170847971245495, -0.8170847971245495, -0...  
1  [[-0.7951157225528295, -0.7951157225528295, -0...  
2  [[-0.811164750246104, -0.811164750246104, -0.6...  
3  [[-0.7238549961538402, -0.7238549961538402, -0...  
4  [[-0.764841488328076, -0.764841488328076, -0.7...

For now, we care about collating the parameter values found for all the subjects, so let's find a way to separate that data out.

In [19]:
df['param'].values

array([array([[0.012],
       [0.005],
       [0.5  ],
       [5.   ],
       [4.   ],
       [1.   ],
       [0.006]]),
       array([[1.19348588e-02],
       [7.41637146e-03],
       [9.67023304e-01],
       [1.44790558e+01],
       [3.95527275e+00],
       [1.79503011e+00],
       [8.75783847e-03]]),
       array([[1.59536762e-02],
       [8.95411001e-03],
       [9.64698673e-01],
       [1.79363935e+01],
       [4.87528989e+00],
       [2.38872919e+00],
       [6.01350502e-03]]),
       array([[1.60129508e-02],
       [8.46146727e-03],
       [9.11866846e-01],
       [7.71816404e+00],
       [4.20777962e+00],
       [2.61087180e+00],
       [5.84550435e-03]]),
       array([[1.56526689e-02],
       [6.11326530e-03],
       [9.65940829e-01],
       [1.86437534e+01],
       [4.42104048e+00],
       [1.39218052e+00],
       [5.00109525e-03]]),
       array([[0.00691254],
       [0.01530229],
       [0.92983616],
       [6.89398281],
       [1.18963888],
       [2.2759142 ],
       [0.